Repository manala/manala-recipes, pull requests merged in 2021-04, with the labels that each got.

#127 Improve elao motd
  elao.app/.manala/ansible/templates/motd/elao.j2
Labels: ready to review

#132 [Elao - App] Network hosts
  elao.app/.manala.yaml
  elao.app/.manala/ansible/inventories/system.yaml.tmpl
  elao.app/.manala/ansible/system.yaml
  elao.app/README.md
Labels: enhancement

#131 [Elao - App] Box update doc
  elao.app/README.md
Labels: documentation
